GestionBibliotheque/Models/BookViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace GestionBibliotheque.Models
{
    public class BookViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Le titre est requis")]
        public string Title { get; set; } = null!;

        [Required(ErrorMessage ="La description est requise")]
        [MaxLength(255, ErrorMessage ="La description est trop longue")]
        public string Description { get; set; } = null!;

        [Required(ErrorMessage = "Le nombre de page est requis")]
        public int Nbpages { get; set; }

        public int AuthorId { get; set; }
   
        public int DomainId { get; set; }
    }
}

GestionBibliotheque/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionBibliotheque.Entities;
using GestionBibliotheque.Infrastructure.Data;
using GestionBibliotheque.Models;

namespace GestionBibliotheque.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;

        public BooksController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            return View();
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorsList"] = new SelectList(_context.Authors.ToList(),"Id", "Firstname");
            ViewData["DomainsList"] = new SelectList(_context.Domains.ToList(), "Id", "Name");

            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookViewModel bvm)
        {
            
            if (ModelState.IsValid)
            {
                var author = await _context.Authors.FindAsync(bvm.AuthorId);
                var domain = await _context.Domains.FindAsync(bvm.DomainId);

                var book = new Book()
                { 
                    Title = bvm.Title,
                    Nbpages = bvm.Nbpages,
                    Description = bvm.Description,
                    Author = author,
                    Domain = domain
                };
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bvm);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Where(b => b.Id == id)
                .Include(a => a.Author)
                .Include(d => d.Domain)
                .FirstOrDefaultAsync();

            if (book == null)
            {
                return NotFound();
            }

            var bvm = new BookViewModel() {
                Id = book.Id,
                Title = book.Title,
                Nbpages = book.Nbpages,
                Description = book.Description,
                DomainId = book.Domain.Id,
                AuthorId = book.Author.Id
            };

            ViewData["AuthorsList"] = new SelectList(_context.Authors.ToList(), "Id", "Firstname");
            ViewData["DomainsList"] = new SelectList(_context.Domains.ToList(), "Id", "Name");

            return View(bvm);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookViewModel bvm)
        {
            if (id != bvm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var author = await _context.Authors.FindAsync(bvm.AuthorId);
                    var domain = await _context.Domains.FindAsync(bvm.DomainId);

                    var book = new Book() {
                        Title = bvm.Title,
                        Nbpages = bvm.Nbpages,
                        Description = bvm.Description,
                        Author = author,
                        Domain = domain
                    };

                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(bvm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bvm);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }

        [HttpPost]
        public JsonResult GetBooksBySearch(string search)
        {
            var books = (from book in _context.Books
                        join rentail in _context.Rentails.OrderByDescending(r => r.Id).Take(1) on book.Id equals rentail.Book.Id into r
                        join author in _context.Authors on book.Author.Id equals author.Id 
                        from rent in r.DefaultIfEmpty()
                        where book.Title.Contains(search) && ((rent == null ) || (rent != null && rent.ReturnDate != null && rent.ReturnDate <= DateTime.Now))
                        select new { book.Title, author.Firstname, author.Lastname, book.Id })
                        .ToList();        
            return Json(books);
        }        
    }
}

GestionBibliotheque/ViewComponents/BookListViewComponent.cs
using GestionBibliotheque.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GestionBibliotheque.ViewComponents
{
    public class BookListViewComponent : ViewComponent
    {
        private LibraryContext Context { get; set; }

        public BookListViewComponent(LibraryContext context)
        {
            Context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int? DomainId, int? AuthorId)
        {
            List<Book> books = new List<Book>();

            if (DomainId != null)
            {
                books = await Context.Books
                    .Include(b => b.Domain)
                    .Include(b => b.Author)
                    .Include(b => b.Rentails.OrderByDescending(r => r.Id).Take(1))
                    .Where(r => r.Domain.Id == DomainId)
                    .ToListAsync();

                //books = (from book in Context.Books
                //             join rentail in Context.Rentails.OrderByDescending(r => r.Id).Take(1) on book.Id equals rentail.Book.Id into r
                //             join author in Context.Authors on book.Author.Id equals author.Id
                //             join domain in Context.Domains on book.Domain.Id equals domain.Id
                //             from rent in r.DefaultIfEmpty()
                //             where ((rent == null) || (rent != null && rent.ReturnDate != null && rent.ReturnDate <= DateTime.Now))
                //             select book)
                //       .ToList();
            }
            else if (AuthorId != null)
            {
                books = await Context.Books
                    .Include(b => b.Domain)
                    .Include(b => b.Author)
                    .Where(r => r.Author.Id == AuthorId)
                    .ToListAsync();
            } else
            {
                books = await Context.Books
                    .Include(b => b.Domain)
                    .Include(b => b.Author)
                    .ToListAsync();
            }
            return View(books);
        }


    }
}

GestionBibliotheque/ViewComponents/RentailListViewComponent.cs
using GestionBibliotheque.Entities;
using GestionBibliotheque.Infrastructure.Data;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.WebSockets;

namespace GestionBibliotheque.ViewComponents
{
    [ViewComponent(Name = "RentailList")]
    public class RentailListViewComponent: ViewComponent
    {
        private LibraryContext Context { get; set; }

        public RentailListViewComponent(LibraryContext context)
        {
            Context = context;
        }
        
        public async Task<IViewComponentResult> InvokeAsync(int? BookId, int? LectorId)
        {
            List<Rentail> rentails = new List<Rentail>();

            if (BookId != null)
            {
                rentails = await Context.Rentails
                    .Include(r => r.Book)
                    .Include(r => r.Lector)
                    .Where(r => r.Book.Id == BookId)
                    .ToListAsync();
            }
            else if (LectorId != null)
            {
                rentails = await Context.Rentails
                    .Include(r => r.Book)
                    .Include(r => r.Lector)
                    .Where(r => r.Lector.Id == LectorId)
                    .ToListAsync();
            }
            else
            {
                rentails = await Context.Rentails
                    .Include(b => b.Book)
                    .Include(b => b.Lector)
                    .ToListAsync();
            }
            return View(rentails);
        }
    }
}

GestionBibliotheque/Views/Books/Create.cshtml
@model GestionBibliotheque.Models.BookViewModel

@{
    ViewData["Title"] = "Create";
    var authorsList = ViewData["AuthorsList"] as IEnumerable<SelectListItem>;
    var domainsList = ViewData["DomainsList"] as IEnumerable<SelectListItem>;
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nbpages" class="control-label"></label>
                <input asp-for="Nbpages" class="form-control" />
                <span asp-validation-for="Nbpages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Autheur</label>
                <select asp-for="AuthorId" asp-items="authorsList" class="form-control"></select>
            </div>

            <div class="form-group">
                <label asp-for="DomainId" class="control-label">Domaine</label>
                <select asp-for="DomainId" asp-items="domainsList" class="form-control"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionBibliotheque/Views/Books/Delete.cshtml
@model GestionBibliotheque.Entities.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nbpages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nbpages)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GestionBibliotheque/Views/Books/Details.cshtml
@model GestionBibliotheque.Entities.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h4>@Model.Title - @Model.Author.Firstname @Model?.Author.Lastname</h4>
<hr></hr>
<div class="row">
    <div class="col-4 jumbotron">
        <ul class="list-group">
            <li class="list-group-item">@Model?.Nbpages pages</li>
            <li class="list-group-item">@Model?.Description</li>
        </ul>
    </div>
    <div class="col-8">
        @await Component.InvokeAsync("RentailList", new { BookId = Model?.Id })
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GestionBibliotheque/Views/Books/Edit.cshtml
@model GestionBibliotheque.Models.BookViewModel

@{
    ViewData["Title"] = "Edit";
    var authorsList = ViewData["AuthorsList"] as IEnumerable<SelectListItem>;
    var domainsList = ViewData["DomainsList"] as IEnumerable<SelectListItem>;
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nbpages" class="control-label"></label>
                <input asp-for="Nbpages" class="form-control" />
                <span asp-validation-for="Nbpages" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="AuthorId" class="control-label">Autheur</label>
                <select asp-for="AuthorId" asp-items="authorsList" class="form-control"></select>
            </div>

            <div class="form-group">
                <label asp-for="DomainId" class="control-label">Domaine</label>
                <select asp-for="DomainId" asp-items="domainsList" class="form-control"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionBibliotheque/Views/Books/Index.cshtml
@model IEnumerable<GestionBibliotheque.Entities.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@await Component.InvokeAsync("BookList")